import turtle
from random import *
from turtle import *
penup()
goto(-140,140)
for sp in range(15):
 speed(10)
 write(sp)
 right(90)
 forward(10)
 pendown()
 forward(150)
 penup()
 backward(160)
 left(90)
 forward(20)
XamBro1 = Turtle()
XamBro1.color('green')
XamBro1.shape('turtle')
XamBro1.penup()
XamBro1.goto(-160,100)
XamBro1.pendown()
XamBro2 = Turtle()
XamBro2.color('red')
XamBro2.shape('turtle')
XamBro2.penup()
XamBro2.goto(-160,80)
XamBro2.pendown()
XamBro3 = Turtle()
XamBro3.color('blue')
XamBro3.shape('turtle')
XamBro3.penup()
XamBro3.goto(-160,60)
XamBro3.pendown()
for turn in range(100):
 XamBro1.forward(randint(1,5))
 XamBro2.forward(randint(1,5))
 XamBro3.forward(randint(1,5))
turtle.done()
